export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
